ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/html

    ProxyPreserveHost Off
    ProxyPass /canary-login/ http://canary-login:8090/
    ProxyPassReverse /canary-login/ http://canary-login:8090/

    <Directory /var/www/html>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>