-- Player-placeable upper floor extension.
-- Uses the same platform item generated by stairs, but manual placement is allowed
-- only while the player is standing on one of their own upper platform tiles.

if not Farming then
	return
end

local FLOOR_ITEM_ID = 408
local FLOOR_COST = 2
local FLOOR_STRUCTURE_TYPE = "floor"
local PLATFORM_STRUCTURE_TYPE = "platform"

Farming.buildCatalog.wood.floor = {
	itemId = FLOOR_ITEM_ID,
	cost = FLOOR_COST,
	label = "Wood Floor",
}

local function positionKey(position)
	return string.format("%d:%d:%d", position.x, position.y, position.z)
end

local function buildError(player, message)
	player:sendExtendedOpcode(Farming.OPCODE, "build|error|" .. tostring(message))
	player:sendCancelMessage(message)
end

local function ownsPlatformAt(playerGuid, position)
	local query = db.storeQuery(string.format(
		"SELECT `id` FROM `player_structures` WHERE `player_id`=%d AND `structure_type`='%s' " ..
		"AND `pos_x`=%d AND `pos_y`=%d AND `pos_z`=%d LIMIT 1",
		playerGuid,
		PLATFORM_STRUCTURE_TYPE,
		position.x,
		position.y,
		position.z
	))
	if not query then
		return false
	end
	Result.free(query)
	return true
end

local function hasAnyStructureAt(position)
	local query = db.storeQuery(string.format(
		"SELECT `id` FROM `player_structures` WHERE `pos_x`=%d AND `pos_y`=%d AND `pos_z`=%d LIMIT 1",
		position.x,
		position.y,
		position.z
	))
	if not query then
		return false
	end
	Result.free(query)
	return true
end

local function hasStairBelow(playerGuid, position)
	local lowerZ = position.z + 1
	local query = db.storeQuery(string.format(
		"SELECT `id` FROM `player_structures` WHERE `player_id`=%d AND `structure_type`='stair' " ..
		"AND `pos_x`=%d AND `pos_y`=%d AND `pos_z`=%d LIMIT 1",
		playerGuid,
		position.x,
		position.y,
		lowerZ
	))
	if not query then
		return false
	end
	Result.free(query)
	return true
end

local function parseEntries(rawPayload)
	local raw = tostring(rawPayload or "")
	local entries = {}
	local seen = {}
	local payload = raw:match("^v2|(.+)$") or raw

	for token in payload:gmatch("[^;]+") do
		local x, y, z = token:match("^(%-?%d+),(%-?%d+),(%-?%d+),?[01]?$" )
		if not x then
			x, y, z = token:match("^(%-?%d+),(%-?%d+),(%-?%d+)$")
		end
		if not x then
			return nil, "Invalid floor position."
		end

		local position = Position(tonumber(x), tonumber(y), tonumber(z))
		local key = positionKey(position)
		if not seen[key] then
			seen[key] = true
			entries[#entries + 1] = position
			if #entries > (Farming.BUILD_MAX_TILES or 40) then
				return nil, string.format("You can queue at most %d floor tiles at once.", Farming.BUILD_MAX_TILES or 40)
			end
		end
	end

	if #entries == 0 then
		return nil, "Select at least one square for the floor."
	end
	return entries
end

local function validateFloorPosition(player, position)
	local playerPosition = player:getPosition()
	local playerGuid = player:getGuid()

	-- Standing on an owned platform is the authoritative definition of being on
	-- the player-built second floor. This prevents manual floor placement at z=7
	-- or on arbitrary native upper floors elsewhere in the map.
	if not ownsPlatformAt(playerGuid, playerPosition) then
		return false, "Wood Floor can only be built while standing on your own second floor."
	end
	if playerPosition.z ~= position.z then
		return false, "Wood Floor must be placed on your current second-floor level."
	end

	local distance = math.max(math.abs(playerPosition.x - position.x), math.abs(playerPosition.y - position.y))
	if distance ~= 1 then
		return false, "Place Wood Floor on one of the 8 squares next to your character."
	end

	-- Never allow the manual floor tool to close the stair shaft again.
	if hasStairBelow(playerGuid, position) then
		return false, "You cannot place floor directly above a stair."
	end

	if hasAnyStructureAt(position) then
		return false, "That upper-floor square already belongs to a player construction."
	end

	local tile = Tile(position)
	if tile then
		local ground = tile:getGround()
		if ground then
			return false, "That upper-floor square already has a floor."
		end
		if tile:hasFlag(TILESTATE_HOUSE) then
			return false, "Building inside houses is disabled."
		end
		if tile:hasFlag(TILESTATE_PROTECTIONZONE) then
			return false, "Building in protection zones is disabled."
		end
		if tile:getCreatureCount() > 0 then
			return false, "A creature is standing on that square."
		end
		if tile:getItemByType(ITEM_TYPE_TELEPORT) then
			return false, "You cannot build floor over a teleport."
		end
	end

	return true
end

local function ensureFloor(position)
	local tile = Tile(position)
	if not tile then
		Game.createTile(position, true)
		tile = Tile(position)
	end
	if not tile or tile:getGround() then
		return nil
	end
	return Game.createItem(FLOOR_ITEM_ID, 1, position)
end

local function cleanupCreated(items)
	for _, item in ipairs(items) do
		if item then
			item:remove()
		end
	end
end

local function deleteRows(playerGuid, positions)
	for _, position in ipairs(positions) do
		db.query(string.format(
			"DELETE FROM `player_structures` WHERE `player_id`=%d AND `structure_type`='%s' " ..
			"AND `pos_x`=%d AND `pos_y`=%d AND `pos_z`=%d",
			playerGuid,
			PLATFORM_STRUCTURE_TYPE,
			position.x,
			position.y,
			position.z
		))
	end
end

local function spendWood(player, amount)
	local wallet = Farming.getWallet(player)
	if (wallet.wood or 0) < amount then
		return false
	end
	local ok = db.query(string.format(
		"UPDATE `player_materials` SET `amount`=`amount`-%d WHERE `player_id`=%d AND `material`='wood' AND `amount`>=%d",
		amount,
		player:getGuid(),
		amount
	))
	if ok then
		Farming.sendWallet(player)
	end
	return ok
end

local function confirmFloor(player, rawPayload)
	local positions, parseError = parseEntries(rawPayload)
	if not positions then
		buildError(player, parseError)
		return true
	end

	for _, position in ipairs(positions) do
		local valid, reason = validateFloorPosition(player, position)
		if not valid then
			buildError(player, reason)
			return true
		end
	end

	local totalCost = FLOOR_COST * #positions
	local wallet = Farming.getWallet(player)
	if (wallet.wood or 0) < totalCost then
		buildError(player, string.format("You need %d wood for this floor.", totalCost))
		return true
	end

	local createdItems = {}
	for _, position in ipairs(positions) do
		local item = ensureFloor(position)
		if not item then
			cleanupCreated(createdItems)
			buildError(player, "The server could not create one of the floor squares.")
			return true
		end
		createdItems[#createdItems + 1] = item
	end

	local values = {}
	for _, position in ipairs(positions) do
		values[#values + 1] = string.format(
			"(%d,'wood','%s',%d,%d,%d,%d)",
			player:getGuid(),
			PLATFORM_STRUCTURE_TYPE,
			FLOOR_ITEM_ID,
			position.x,
			position.y,
			position.z
		)
	end
	if not db.query(
		"INSERT INTO `player_structures` (`player_id`,`material`,`structure_type`,`item_id`,`pos_x`,`pos_y`,`pos_z`) VALUES " ..
		table.concat(values, ",")
	) then
		cleanupCreated(createdItems)
		buildError(player, "Those floor squares could not be reserved.")
		return true
	end

	if not spendWood(player, totalCost) then
		cleanupCreated(createdItems)
		deleteRows(player:getGuid(), positions)
		buildError(player, "Your wood balance changed before the floor was confirmed.")
		return true
	end

	-- Platforms are walkable support and intentionally do not reserve the square
	-- against walls/catapults that may be placed on top later.
	for _, position in ipairs(positions) do
		Farming.structurePositions[positionKey(position)] = nil
		position:sendMagicEffect(CONST_ME_BLOCKHIT)
	end

	local newWallet = Farming.getWallet(player)
	player:sendExtendedOpcode(
		Farming.OPCODE,
		string.format("build|success|wood|%s|%d|%d|%d|0", FLOOR_STRUCTURE_TYPE, #positions, totalCost, newWallet.wood or 0)
	)
	player:sendTextMessage(
		MESSAGE_EVENT_ADVANCE,
		string.format("Built %d upper floor square%s for %d wood.", #positions, #positions == 1 and "" or "s", totalCost)
	)
	if Farming.sendSiegeStatus then
		Farming.sendSiegeStatus(player)
	end
	return true
end

local baseConfirmBuild = Farming.confirmBuild
function Farming.confirmBuild(player, material, structureType, rawPayload)
	if material == "wood" and structureType == FLOOR_STRUCTURE_TYPE then
		return confirmFloor(player, rawPayload)
	end
	return baseConfirmBuild(player, material, structureType, rawPayload)
end

local baseSendBuildCatalog = Farming.sendBuildCatalog
function Farming.sendBuildCatalog(player)
	baseSendBuildCatalog(player)
	player:sendExtendedOpcode(
		Farming.OPCODE,
		string.format("catalog2|wood|%s|%d|%d|%d", FLOOR_STRUCTURE_TYPE, FLOOR_ITEM_ID, FLOOR_ITEM_ID, FLOOR_COST)
	)
end
