# syntax=docker/dockerfile:1.7

FROM ubuntu:24.04 AS dependencies

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
ENV TZ=Etc/UTC

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    libtool \
    mono-complete \
    ninja-build \
    pkg-config \
    python3 \
    tar \
    tzdata \
    unzip \
    zip \
    && ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY vcpkg.json /opt
RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ' | tr -d '\r\n') \
    && echo "vcpkg commit ID: '$vcpkgCommitId'" \
    && git clone https://github.com/microsoft/vcpkg.git \
    && cd vcpkg \
    && git fetch origin \
    && git checkout "$vcpkgCommitId" \
    && ./bootstrap-vcpkg.sh

WORKDIR /opt/vcpkg_manifest
COPY vcpkg.json /opt/vcpkg_manifest/
RUN --mount=type=cache,target=/opt/vcpkg/downloads \
    --mount=type=cache,target=/opt/vcpkg/buildtrees \
    --mount=type=cache,target=/opt/vcpkg/packages \
    --mount=type=cache,target=/root/.cache/vcpkg \
    /opt/vcpkg/vcpkg install \
    --x-manifest-root=/opt/vcpkg_manifest \
    --x-install-root=/opt/vcpkg_installed \
    --triplet=x64-linux \
    --host-triplet=x64-linux

FROM dependencies AS build
WORKDIR /srv/build
COPY src ./src
COPY cmake ./cmake
COPY recompile.sh CMakeLists.txt CMakePresets.json vcpkg.json ./
COPY --from=dependencies /opt/vcpkg_installed ./vcpkg_installed

RUN export VCPKG_MANIFEST_INSTALL=OFF \
    && export VCPKG_INSTALLED_DIR=/srv/build/vcpkg_installed \
    && ./recompile.sh "/opt"

FROM ubuntu:24.04 AS prod
COPY --from=build /srv/build/build/linux-release/bin/canary /bin/canary
WORKDIR /srv/canary
ENTRYPOINT ["/srv/canary/start.sh", "canary"]